[ADD] github project

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -2,32 +2,77 @@ name: chocolatine
 
 on:
   push:
-    branches:
-      - '**'        # matches every branch
-      - '!ga-ignore-*'   # excludes ga-ignore-
+    branches-ignore:
+      - "ga-ignore"
   pull_request:
-    branches: 
-      - '**'        # matches every branch
-      - '!ga-ignore-*'   # excludes ga-ignore-
+    branches-ignore:
+      - "ga-ignore"
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
+env:
+  MIRROR_URL: "git@github.com:Remi-Mergen/chocolatine-mirror.git"
+  EXECUTABLES: ""
 
 jobs:
-  # This workflow contains a single job called "build"
-  build:
+  check_repo:
+    name: "Check if the repo is clean"
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - id: check_repo
+        run: |
+          BAD_FILES=$(find . -type f -not -path "./.git/*" -wholename "*tmp/*" -or -iname "*pain_au_chocolat*" -or -name "*~" -or -name "*.o" -or -name "*.a" -or -name "*.so" -or -name "*.gcno" -or -name "*.gdca" -or -name "*.gcov")
+          for FILES in $BAD_FILES; do
+            echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
+          done
+          if [ "$BAD_FILES" != ""]; then
+            exit 1
+          fi
+
+  check_if_compil:
+    needs: [check_repo]
+    name: "check if the make compil"
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
+
+    steps:
+      - uses: actions/checkout@v3
+      - id: check_if_compil
+        run: make
+        timeout-minutes: 2
+      - run: make clean
+      - run: |
+          OIFS=$IFS
+          IFS=','
+          for x in $EXECUTABLES
+            do
+              ./$x
+            done
+          IFS=$OIFS
+
+  run_tests:
+    needs: check_if_compil
+    name: "Run the tests"
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
+
+    steps:
+      - uses: actions/checkout@v3
+      - id: run_tests
+        run: make tests_run
+        timeout-minutes: 2
+
+  push_to_mirror:
+    needs: [check_if_compil]
+    if: ${{ github.event_name == 'push' }}
+    name: "Push to mirror"
     runs-on: ubuntu-latest
 
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          find . -name "*.a" -o -name "*.exe" -o -name "*.o" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -name "*~" -o -name "#*#"
-          echo test, and deploy your project.
+      - uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          target_repo_url:
+            ${{ env.MIRROR_URL }}
+          ssh_private_key:
+            ${{ secrets.Key }}
